apiVersion: v1
kind: Pod
metadata:
  name: memory-consumer
spec:
  containers:
  - name: memory-consumer-container
    image: msepehr/oom:4.1
    resources:
      requests:
        memory: "6000Mi"
      limits:
        memory: "6000Mi"
    env:
    - name: MEM_TEST
      value: "10000"
        